version: '3'

# https://coursehunter.net/course/angular-4-c-nulya-do-profi
# docker run --name angular8 -it -v $(pwd)/app:/my-project:rw -p 9876:9876 -p 4200:4200 angular_cli:install bash
services:
  app:
    build:
      dockerfile: Dockerfile
      context: ./app
      args:
        NAME_PROJECT: my-project
    stdin_open: true
    tty: true
    ports:
      - 4200:4200
      - 9876:9876
    volumes:
      - ./app:/my-project
